version: '3.8'

services:
  profile-api:
    image: postgres
    env_file:
      - .env
    container_name: profile-api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5434:5432"
    networks:
      - profile-api-network
    restart: always

networks:
  profile-api-network:
    driver: bridge
