version: '3.8'

services:
  profile-test-api:
    image: postgres
    env_file:
      - path: .env.test
        required: true
    container_name: profile-test-api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - profile-test-api-network
    restart: always

networks:
  profile-test-api-network:
    driver: bridge
