export enum RabbitMqQueues {
    PROFILE_RESPONSE_QUEUE = 'PROFILE_RESPONSE_QUEUE',
    VALIDATE_USER_SESSION = 'VALIDATE_USER_SESSION',
    UPDATE_USER_WITH_SELECTED_PROFILE_ID = 'UPDATE_USER_WITH_SELECTED_PROFILE_ID',
    CHECK_PHONE_NUMBER_DISPONIBILITY = 'CHECK_PHONE_NUMBER_DISPONIBILITY',
    CHECK_EMAIL_DISPONIBILITY = 'CHECK_EMAIL_DISPONIBILITY',
    UPDATE_USER_WITH_PHONE_NUMBER = 'UPDATE_USER_WITH_PHONE_NUMBER',
    CREATE_TOKEN = 'CREATE_TOKEN',
    VALIDATE_TOKEN = 'VALIDATE_TOKEN',
    CREATE_PROFILE_AFTER_SIGNUP = 'CREATE_PROFILE_AFTER_SIGNUP',
};
