export enum RabbitMqQueues {
    PROFILE_RESPONSE_QUEUE = 'PROFILE_RESPONSE_QUEUE',
    VALIDATE_USER_SESSION = 'VALIDATE_USER_SESSION',
    UPDATE_USER_WITH_PROFILE_DATA = 'UPDATE_USER_WITH_PROFILE_DATA',
    CHECK_PHONE_NUMBER_DISPONIBILITY = 'CHECK_PHONE_NUMBER_DISPONIBILITY',
};
