import "reflect-metadata";
import express from "express";
import routes from "./routes";
import './database';
import cors from 'cors';
import clientErrorHandle from "./errors/client-error-handler";
import { validateUserToken } from "./utils/validate-user-token";
const app = express();
app.use(express.json());
app.use(cors());
app.use(validateUserToken);
app.use(clientErrorHandle);
app.use(routes);
export default app;
