import "reflect-metadata";
import express from "express";
import routes from "./routes";
import './database';
import cors from 'cors';
import { VALIDATE_TOKEN } from "./constants/validate-token";
import { clientErrorHandle } from "millez-lib-api";
const app = express();
app.use(express.json());
app.use(cors());
app.use(VALIDATE_TOKEN.validate);
app.use(routes);
app.use(clientErrorHandle);
export default app;
